# Site settings
title: MINI BIKE FEST
description: May 30th, 2026 - Berlin - craftwerk.berlin - 12-8pm
baseurl: "/mini_bike_fest"
url: "https://falkorichter.github.io"

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/
